### ISSUE TITLE
数组越界

### ISSUE THREAD

**Issue by CodeFish99** [Akane0721/OrpheusNet#1]
测试样例用的是example里的《上海红茶馆》，把五线谱的部分切掉只留简谱，报错信息如下
```
Traceback (most recent call last):
  File "C:\Users\10470\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\10470\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\10470\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\10470\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\10470\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\10470\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "d:\project\OrpheusNet\app.py", line 23, in upload_file
    result_file = image2midi(image_path=os.path.join('uploads', filename),
  File "d:\project\OrpheusNet\main.py", line 68, in image2midi
    lines = image_segmentation(image_path)
  File "d:\project\OrpheusNet\imageprocess.py", line 64, in image_segmentation
    rows = horizontal_protection(image, min_height=3, merge=True)
  File "d:\project\OrpheusNet\imageprocess.py", line 26, in horizontal_protection
    merged_row_ranges = [row_ranges[0]]
IndexError: list index out of range
```

**Comment by poppy279** [comment]
Hello, is there a pths for VGG modeling? Can you please tell me what notes are currently recognized by this project? I imported my score and it seems that some of them are not recognized, looking forward to a reply, thanks!
